apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibkr-client.fullname" . }}
  labels:
    {{- include "ibkr-client.labels" . | nindent 4 }}
data:
  app-name: {{ .Values.config.appName | quote }}
  app-env: {{ .Values.config.appEnv | quote }}
  app-debug: {{ .Values.config.appDebug | quote }}
  app-version: {{ .Values.config.appVersion | quote }}
  http-port: {{ .Values.config.httpPort | quote }}
  grpc-port: {{ .Values.config.grpcPort | quote }}
  log-level: {{ .Values.config.logLevel | quote }}
  db-log-level: {{ .Values.config.dbLogLevel | quote }}
  ibkr-gateway-url: {{ .Values.config.ibkrGatewayURL | quote }}
  mtls-enabled: {{ .Values.config.mtlsEnabled | quote }}
  otel-collector-endpoint: {{ .Values.config.otelCollectorEndpoint | quote }}
