apiVersion: v2
name: ibkr-client
description: IBKR Client Portal Gateway middleware service
type: application
version: 0.1.19
appVersion: "v0.1.5"
keywords:
  - ibkr
  - trading
  - middleware
maintainers:
  - name: Majid Mvulle
home: https://github.com/majidmvulle/ibkr-client
