name: Lint Golang Code
on:
  pull_request:
    branches:
      - main
    paths:
      - '**/**.go'
      - '**/go.mod'
      - '**/go.sum'

concurrency:
  group: ci-lint-golang-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-golang:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Go environment
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          check-latest: true

      - name: Install dependencies
        run: go get ./...

      - name: Run Go mod tidy
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --out-format=github-actions
          version: v2.6
